# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2019-11-06 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note_app', '0002_remove_document_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='notecomment',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
