# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2019-11-01 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note_app', '0002_remove_notecomment_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='notecomment',
            name='isCode',
            field=models.BooleanField(default=False),
        ),
    ]
