# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2019-12-11 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note_app', '0003_comment_indentlevel'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebook',
            name='position_id',
            field=models.IntegerField(null=True),
        ),
    ]
